name = "hklcv-theme"
license = "MIT"
licenselink = "https://github.com/kunlunh/hklcv-theme/blob/master/LICENSE"
description = "A clean and simple resume theme for Hugo"
homepage = "https://github.com/kunlunh/hklcv-theme"
tags = ["resume", "cv", "portfolio"]
features = ["responsive"]
min_version = "0.41.0"

[author]
  name = "HUANG, Kunlun"
  homepage = "https://kunlunh.github.io/"
