name: Upyun Deploy Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    TZ: Asia/Shanghai # 设置当前环境时区

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git Configuration
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Setup Hugo
        uses: kevvurs/action-hugo@v1.0-rc2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Build
        run:
          hugo --minify
          
      - name: deploy-upyun
        uses: bwcxyk/upyun-upx-action@1.3
        env:
          UPX_SERVICENAME: ${{ secrets.UPX_SERVICENAME }}
          UPX_OPERATOR: ${{ secrets.UPX_OPERATOR }}
          UPX_PASSWORD: ${{ secrets.UPX_PASSWORD }}
          LOCAL_DIR: ./public/
          REMOTE_DIR: /
